name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy-action@v1.2
        with:
          railwayToken: ${{ secrets.STATUS_RAILWAY_TOKEN }}
          projectId: 3658acad-ba45-42aa-b1fb-dd0e6425e29f
